#!/bin/bash

### must include and placed in $HOME ----> https://github.com/S3xyL1nux/S3xyL1nux/blob/master/dictionary.txt

START=$(date +%s.%N)

echo
echo -e "          \e[5m\e[32m********************************\e[0m"
echo -e "          \e[5m\e[32m* \e[0m\e[92m\e[1mS3xyL1nux offline dictionary\e[0m \e[5m\e[32m*\e[0m"
echo -e "          \e[5m\e[32m********************************\e[0m"

word1=$1
word2=`echo "${word1^}"`

if [ -z $word1 ]; then
echo -e "\e[1m\e[3$(( $RANDOM * 6 / 32767 + 1 ))menter word\e[0m"
read word1
word2=`echo "${word1^}"`
fi

if [ -z $word1 ]; then
echo -e "\e[1m\e[3$(( $RANDOM * 6 / 32767 + 1 ))myou didn't set any word....\e[0m"
echo
echo -e "\e[1m\e[3$(( $RANDOM * 6 / 32767 + 1 ))mexit.\e[0m"
echo
exit 1
fi

read=`grep ^$word2 $HOME/dictionary.txt | head -1`

if [[ -n $word1 ]] && [[ -n $read ]]; then
echo
echo -e "\e[1m\e[3$(( $RANDOM * 6 / 32767 + 1 ))m$read\e[0m"
echo
fi

if [[ -n $word1 ]] && [[ -z $read ]]; then
echo
echo -e "\e[1m\e[3$(( $RANDOM * 6 / 32767 + 1 ))mno result found.\e[0m"
echo
fi

END=$(date +%s.%N)
DIFF=$(echo "$END - $START" | bc)

echo -e "\e[1m\e[3$(( $RANDOM * 6 / 32767 + 1 ))mloading time $DIFF seconds\e[0m"
echo -e "\e[1m\e[3$(( $RANDOM * 6 / 32767 + 1 ))mexit.\e[0m"
